### ISSUE TITLE
Helm Panel LEDs

### ISSUE THREAD

**Issue by pblo** [afarran/swm2m_vms_tests#11]
I think we need more information in documentation.

Some knowledge we've investigated, but anyway confirmation would be great.

According to this picture from documentation:

https://github.com/afarran/swm2m_vms_tests/blob/master/screens/ledsofhelm.jpg

We have LEDs and properties of unibox:

1) Connect  -> led1State
2) GPS  -> led2State
3) Sat -> led3State
4) Power -> led4State

Seems to be confirmed by TCs ..

Is there any more detailed description of roles of each LED ? 

each LED can be in state: OFF or  SLOW_FLASH or FAST_FLASH or ON

It would be nice to have something more descriptive in documentation ,  like a list: 

LED_NAME |LED_NO(unibox)| STATE(eg OFF or ON) | REASON(descriptive meaning) | Event (if any)

Thanks for feedback.

**Comment by ArturMalyszewicz** [comment]
There is a property MinStandardReportLedFlashTime (PIN 101) - in seconds, the minimum period of time the Terminal Connected LED is flashing when standard report is being sent. 
Should the Terminal Connected LED be flashing SLOW or FAST?

**Comment by afarran** [comment]
|  | External Power | 1. Terminal Connected | 2. GPS | 3. Satellite | 4. |
| --- | --- | --- | --- | --- | --- |
| Off | No power to IDP/Helm | IDP is not connected to Helm panel | GPS is unavailable | Sat link is unavailable | - |
| Flash Slowly | - | To-mobile email is unread | - | Sat link is being established | - |
| Flash Fast | - | From-mobile standard/email msg is being sent | - | - | - |
| On | Green (ext. pwr), Blue (batt. pwr) | IDP terminal is connected to Helm panel | GPS is ok | Sat link is ok | - |
