### ISSUE TITLE
Normal reports - accelerated reports rate.

### ISSUE THREAD

**Issue by pblo** [afarran/swm2m_vms_tests#12]
In most test cases we use values to calculate accelerated report interval as an integer, like:

4/2=2 minutes
2/2=1 minute

I've just added TC to check what will happen when values are not giving total number but rather float, for example:

2/3 = 0.66 (40 secs)

but observed interval is 60secs , should it be 40 secs ? 

In this case : 4/3 = 1.33 (80 secs) , observed interval is 80 secs.

Is it correct that intervals less than minute are not calculated, but one minute is placed instead?

**Comment by afarran** [comment]
1 minute is used for calculated intervals that result in less than a minute value.

**Comment by afarran** [comment]
This is already documented under Rpt.html:

> The minimum interval between reports from same reporting service is 60 seconds. 
> This minimum interval is applied to 
> - two Standard reports, 
> - two Accelerated reports,
> - two Log reports,
> - consecutive Standard and Accelerated reports, or
> - consecutive Standard and Log reports
