### ISSUE TITLE
Discrepancy between requirements and implementation in case displaying the Transmit Message Status 

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_vms_tests#14]
In document 002 M2M0030RA001 VMS Phase 1 Requirements Analysis there is an requirement:
`UICTL.3.6 By default, displaying the Transmit Message Status is disabled.`
But for current implementation the default value of MinStandardReportLedFlashTime  (PIN101) is 10 seconds so Transmit Message Status is not disabled.

Also documentation says that minimum time for flashing LED is 10 seconds but VMS allows setting this time below that value. 

Have requirements mentioned above been changed meantime?

**Comment by afarran** [comment]
No, the requirements haven't changed. There are two minor issues:
1. default value is not disabled
2. minimum flashing time can be less than 10 seconds

**Comment by ArturMalyszewicz** [comment]
OK. Will split it to two bugs.
