### ISSUE TITLE
PowerDisconnected AbnormalReport does not contain last saved position information prior to power-off

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_vms_tests#22]
AbnormalReport is generated with PowerDisconnected state set to true after PowerDisconnectedEndDebounceTime. The message should contain last saved position information prior to power-off. But despite the GPS position is saved in params file report contains current position.

Steps to reproduce:
1. Set PowerDisconnectedStartDebounceTime to 1 second
2. Simulate terminal in InitialPosition 
3. Wait for PROPERTIES_SAVE_INTERVAL (10 minutes) to make sure terminal saved params.
4. Restart terminal (switching off simulated)
5. Change simulated position to AfterRebootPosition - different than InitialPositon
6. Wait until terminal is up and receive AbnormalReport with PowerDisconnected information 
7. Check if AbnormalReport containts GPS information from InitialPositon

In example this is the content of the params file that was saved during the run of TC:
- Before TC:
  P{sysTime=1422871869,course=0,longitude=60000,fixTime=1422871868,speed=0,latitude=60000,}
  1422871869 = 11:11:09
- Message arrives at 1422872222 = 11:17:02 (no save of parameters meanwhile) with gps informaton longitude=300000, latitude=300000 (AfterRebootPosition not InitialPosition) 

Related TC: test_PowerDisconnected_WhenTerminalIsOffForTimeAbovePowerDisconnectedStartDebouncePeriod_PowerDisconnectedAbnormalReportIsSentWhenTerminalIsOnAgain

**Comment by afarran** [comment]
Argus 21572

**Comment by ArturMalyszewicz** [comment]
In 1.4.1 last saved position is reported but there is an issue with Course field: #43
