### ISSUE TITLE
Commands with only <CR> char are accepted and executed 

### ISSUE THREAD

**Issue by brabiega** [afarran/swm2m_vms_tests#25]
**Current behavior:**
“HELO[CR]” <-> 250 OK
**Expected behavior:**
“HELO[CR]” <-> No response until [CRLF] is issued
**RFC:**
Lines consist of zero or more data characters terminated by the sequence ASCII character "CR" (hex value 0D) followed immediately by ASCII character "LF" (hex value 0A).  This termination sequence is denoted as [CRLF] in this document.  Conforming implementations MUST NOT recognize or generate any other character or character sequence as a line terminator.  Limits MAY be imposed on line lengths by servers (see Section 4).
In addition, the appearance of "bare" "CR" or "LF" characters in text (i.e., either without the other) has a long history of causing problems in mail implementations and applications that use the mail system as a tool.  SMTP client implementations MUST NOT transmit these characters except when they are intended as line terminators and then MUST, as indicated above, transmit them only as a [CRLF] sequence.
**Comment:**
This issue creates more problems – the line terminator of Terminal Simulator console is only [CR] char (it can be seen on trace output in SMTP mode). This works fine for typical console commands but makes problems in SMTP mode. DATA command requires [CRLF].[CRLF] sequence of chars to terminate the DATA which is correct and implemented as specified in RFC, however I haven’t found a way to send that sequence from Terminal Simulator console (How to type [LF] char?). Perhaps Terminal Simulator console should always send [CRLF]. The question is whether only [CR] command terminator should be accepted by SMTP server – according to RFC it shouldn’t – the correct way is [CRLF]. 

**Related TC:**
test_SMTP_WhenTextEndedWithCRInsteadOfCRLFAreIsSent_TextIsNotTreatedAsCommand

**Comment by afarran** [comment]
Not sure what you mean by **No response until is issued**. In general, I wouldn't recommend using SkyWave's Console application to test this serial link. Instead, I recommend using an independent console application like Putty or TeraTerm to represent the e-mail client. Such applications provide more control over sending CR, LF, echoing, etc.

I also recommend using Docklight for monitoring the serial link between the client and IDP terminal.

**Comment by brabiega** [comment]
I've used other tools to test SMTP - mainly Putty and RealTerm.

I've updated the description - unfortunately GitHub does not render angle brackets, I've changed them to []. I believe the description is more clear now,

**Comment by brabiega** [comment]
Issue still occurs

**Comment by afarran** [comment]
Can't reproduce the issue in v1.4.1. Please include trace output showing the command is processed following a <CR> and not following a <CR><LF>

**Comment by brabiega** [comment]
My mistake... The testcase had wrong assertion. 

The issue no longer occurs in VMS v1.4.1.
