### ISSUE TITLE
Default values for Standard Reports.

### ISSUE THREAD

**Issue by pblo** [afarran/swm2m_vms_tests#35]
The documentation states:

Default value for StandardReport1Interval is 60
Default value for StandardReport2Interval is 0
Default value for StandardReport3Interval is 0

I'm just asking : is that correct? The default value for StandardReport1Interval shoud be different than the others?

**Comment by afarran** [comment]
Yes, basically "Service 1" reporting is enabled, while the other reporting services are disabled by default. You can find actual default values of properties like this:

```
shell> prop get VMS StandardReport1Interval ?
   Name: StandardReport1Interval
   Type: UNSIGNED
Storage: CONFIG
Default: 60
    Min: 0
    Max: 1440
```
