### ISSUE TITLE
InterfaceUnitDisconnectedState (PIN 49) is not changing according to uniboxConnected property (PIN 12) in UniboxInOut service

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_vms_tests#37]
UniboxConnected (PIN 12) property in UniboxInOut service does not control the InterfaceUnitDisconnectedState.  

IMPORTANT: Special helper service has been created with only 5 properties:
1. PIN=2(led1State) val=OFF
2. PIN=3(led2State) val=FAST
3. PIN=4(led3State) val=ON
4. PIN=5(led4state) val=OFF
5. PIN=12(uniboxConnected) val=true

Steps to reproduce:
1. Disable UniboxInOut service to put terminal into InterfaceUnitDisconnectedState = true 
2. Set InterfaceUnitDisconnectedEndDebounceTime to 1 second
3. Enable UniboxInOut service 
4. Set UniboxConnected (PIN 12) to true (interface unit connected)
5. Wait for longer the InterfaceUnitDisconnectedEndDebounceTime 
6. Check InterfaceUnitDisconnectedState property - it has not been changed.

Trace output from scenario described above attached below:

```
[ 12:45:26.113 ] [26:INFO] CLI Thread: starting
[ 12:45:28.288 ] [18:INFO] completed RL msg #4 (SIN=115), status=Success
[ 12:45:28.289 ] [18:INFO] completed RL msg #5 (SIN=115), status=Success
[ 12:45:42.266 ] [26:INFO] CLI Cmd: [prop set VMS 47 1]
[ 12:45:42.267 ] [16:INFO] config changes for service 'VMS'
[ 12:45:46.270 ] [26:INFO] CLI Cmd: [prop set VMS 48 1]
[ 12:45:46.271 ] [16:INFO] config changes for service 'VMS'
[ 12:45:51.704 ] [26:INFO] CLI Cmd: [prop get VMS]
[ 12:46:08.519 ] [26:INFO] CLI Cmd: [prop get 162]
[ 12:47:22.999 ] [115:INFO] Event HwClientDisconnected changed to true 
[ 12:47:22.999 ] [115:INFO] Event InterfaceUnitDisconnected changed to true
[ 12:47:23.009 ] [18:INFO] queuing RL msg #6 (SIN=115, bits=156)
[ 12:47:23.009 ] [18:INFO] sending RL msg #6 trn #1 (SIN=115, bits=156)
[ 12:47:23.018 ] [115:INFO] Event IdpBlocked changed to true
[ 12:47:23.027 ] [18:INFO] queuing RL msg #7 (SIN=115, bits=156)
[ 12:47:23.027 ] [18:INFO] sending RL msg #7 trn #1 (SIN=115, bits=156)
[ 12:47:28.986 ] [18:INFO] completed RL msg #6 (SIN=115), status=Success
[ 12:47:28.986 ] [18:INFO] completed RL msg #7 (SIN=115), status=Success
[ 12:47:43.976 ] [26:INFO] CLI Cmd: [prop get VMS]
[ 12:47:57.362 ] [26:INFO] CLI Cmd: [prop get 162]
[ 12:48:28.361 ] [26:INFO] CLI Cmd: [prop set 162 12 true] 
[ 12:48:36.744 ] [26:INFO] CLI Cmd: [prop get VMS]
[ 12:49:03.233 ] [26:INFO] CLI Cmd: [prop get VMS]
[ 12:49:53.697 ] [26:INFO] CLI Cmd: [prop get VMS]
```

**Comment by afarran** [comment]
Changing the property is not enough. When the Unibox connection state changes, the UniboxConnected property changes and an event is posted as per the Unibox API document. It seems that you simulated the change in the property but not in the event.

**Comment by ArturMalyszewicz** [comment]
Yes, that's right. We added Unibox event on property change and now it works. Thanks for help.
