### ISSUE TITLE
Documentation of Mail Module

### ISSUE THREAD

**Issue by brabiega** [afarran/swm2m_vms_tests#40]
The documentation contains a sentence with question mark.

> Receiving e-mails from the Internet
> 
> (...)
> The terminal's e-mail address follows this format [mobileID]@isatdatapro.skywave.com?

It looks like a minor bug.

PS. I'm not sure how to specify expected behaviour in this case :)

**Comment by afarran** [comment]
The question mark is not a bug, it's a documentation issue to Product Management. The terminal may have different e-mail addresses including the one in the documentation and we're still not sure what the PM's position on documenting all supported e-mail addresses.

**Comment by brabiega** [comment]
Not an issue.
