### ISSUE TITLE
POP3 retrieving messages (LIST command).

### ISSUE THREAD

**Issue by pblo** [afarran/swm2m_vms_tests#44]
Hi, 

It seems VMS does not persist email messages or does not update messages list.

We are performing following steps in the TC:
1. Using smtp to send test email.
2. Using pop3 to retrieve list of messages (LIST command of pop3 protocol).
3. In the response there is always 0 instead 1 or more.

This is smtp session:

```
mail> smtp
220 00000000SKYEE3D.isatdatapro.skywave.com SMTP Service Ready
HELO
250 Hello from 00000000SKYEE3D IDP terminal
MAIL FROM:<pblo@pblo.com>
250 OK
RCPT TO:<pblo@skywave.com>
250 OK
DATA
354 OK, Send data ending with <CR><LF>.<CR><LF>
From: pblo@pblo.com
To: pblo@skywave.com, 
Subject: Test subject

Some special message data

.
250 97 bytes received. Message queued as 0
QUIT
221 bye

```

This is pop session:

```
mail> pop3
+OK 00000000SKYEE3D.isatdatapro.skywave.com POP3 Service Ready
USER pblo@skywave.com
+OK  pblo@skywave.com accepted
PASS abcd123
+OK password accepted
LIST
+OK 0 messages
quit
+OK bye
```

It looks like bug, doesn't it?

**Comment by pblo** [comment]
This is trace output for this issue: https://github.com/afarran/swm2m_vms_tests/blob/dev/TraceOutputs/Issue%2344/trace.txt.

We also used TCP bridge to send email via outlook and it is the same , stil zero messages in inbox.

We've tried on simulator and idp-680.

**Comment by afarran** [comment]
The POP3 server on IDP terminal shows messages sent successfully to _<terminal ID>@isadatapro.skywave.com_.
So when you send an e-mail to _pblo@skywave.com_ as in your example, that doesn't go to the terminal.
