### ISSUE TITLE
Sending email with 1 allowed and 1 disallowed recipient

### ISSUE THREAD

**Issue by brabiega** [afarran/swm2m_vms_tests#45]
It is not described in the documentation how VMS will behave in situation when an email is sent to two recipients, where recipient A is allowed and recipient B is not allowed.

Example:

>   AllowedEmailDomains = "skywave.com,sky.com"
> 
> MAIL FROM:skywave@sky.com
> RCPT TO:receiver1@sky.com
> RCPT TO:receiver2@notallowed.com
> DATA
> email body
> \r\n.\r\n
> 
> Response is 250 OK

I think there should be a note saying that email will be sent only to allowed domain and disallowed one will be omitted without any error.

**Comment by afarran** [comment]
There's an outstanding feature to send a "failed delivery" e-mail to the originator in such cases. Not sure if we want to put that as part of the SMTP responses.

**Comment by brabiega** [comment]
I agree, it's not the responsibility of SMTP server/protocol.
