### ISSUE TITLE
POP3 : is command UIDL implemented ?

### ISSUE THREAD

**Issue by pblo** [afarran/swm2m_vms_tests#46]
Hi, 

Question about UIDL command in VMS POP3 implementation:

Does it implemented?

When trying to sent:

```
UIDL 1 1
```

I have:

```
-ERR syntax error
```

It is error like for command which does not exists..

**Comment by pblo** [comment]
The same question for : APOP command.

I assume APOP is not needed.

**Comment by afarran** [comment]
You can see a list of implemented commands using the _CAPA_ POP3 command. For _UIDL_ did you have messages in your mailbox that you're trying to query their IDs?
It helps when you provide the full session transactions up to the error message.

**Comment by pblo** [comment]
OK.

UIDL without parameters does not respond with syntax error.

**Comment by afarran** [comment]
Why should it return a syntax error? Please review the RFC for this command and reference your expected behaviour to the RFC.

**Comment by pblo** [comment]
It was my mistake. I passed two parameters.

UIDL takes only one parameter  (optional), according to rfc:

```
UIDL [msg]

      Arguments:
          a message-number (optional), which, if present, may NOT
          refer to a message marked as deleted

```
