### ISSUE TITLE
StandardReports are being sent in packs of 10 every minute after terminal was disconnected from ModemSimulator

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_vms_tests#47]
Terminal was left powered on for long time with ModemSimulator disconnected (PC switched off). The configuration was: PIN=2(StandardReport1Interval) val=1 and PIN=3(AcceleratedReport1Rate) val=1, When terminal was connected back to ModemSimulator there it started to send packs of 10 StandardReports with interval of 1 minute. 

In trace output there were following prints: 

```
[   107.509:22:ltrc] [18:INFO] completed RL msg #24 (SIN=115), status=Failure
[   107.553:22:ltrc] [18:INFO] completed RL msg #25 (SIN=115), status=Failure
[   107.573:22:ltrc] queue 'svc.VMS TX_STATUS'[20:20] is full
[   107.577:22:ltrc] queue 'svc.VMS TX_STATUS'[20:20] is full
```

After some time (apparently when all outstanding reports were sent) terminal acted 'normally' sending single StandardReport every minute. 

Question: is that correct behaviour? Should all outstanding StandardReports be sent in packs of 10 when connection to modem is retrieved?

**Comment by afarran** [comment]
Yes, that seems to be correct. The documentation states:

> All queued from-mobile messages are persistent (i.e. can survive blockage and power-interruption) for a period specified in SIN=18(message) PIN=3(lifetime) property.
