### ISSUE TITLE
ConfigChangeReports and resetProperties

### ISSUE THREAD

**Issue by pblo** [afarran/swm2m_vms_tests#5]
It seems reset of properties does not trigger config change report.

In this scenario Config Change Report hadn't been sent :

1 - Value before reset : AcceleratedReport2Rate = 2
2 - Value just after reset: AcceleratedReport2Rate = 1
3 - (delay of 65 secs)
4 - Value after reset: AcceleratedReport2Rate = 2

It seems values from step 1 and step 4 were compared (and it should have been values from step 2 and step 4).

Or maybe debounce timeout exists for this feature?

**Comment by afarran** [comment]
How did you reset the properties? VMS users would be able to reset properties in one of two ways: using shell commands or using the to-mobile VMS messages SetConfigReport and SetProperties.

**Comment by pblo** [comment]
I reset by SystemServiceWrapper:resetProperties(vms.sin) and this method uses message resetProperties (of system service).

This reset is done only in suite_setup() ..

**Comment by afarran** [comment]
VMS users will not have access to this message. That's why VMS agent provides a VMS dedicated messages to change VMS properties OTA.
If you (or Customer Support) change properties using Core service messages, then I think this would be similar to changing properties using the shell, in which case a debounce-time (PropertyChangeDebounceTime PIN 100) is used.

**Comment by pblo** [comment]
This reset is needed as a cleanup for test environment - just in case previous suite set wrong values.

I think in every suite_setup() we should reset properties to default and the easiest way to do that is use of resetProperties message..

Yes, I took into account PropertyChangeDebounceTime and it is set to 1 in suite_setup().

**Comment by afarran** [comment]
You can use the resetProperties message for setup/teardown but not for VMS test cases. You were asking about not triggering a config change report.

**Comment by pblo** [comment]
Yes, I was running only one TC, thats why it interfered with resetProperties in suiteSetup()

I solved that by changing properties after TC start then waiting for report and sending the message SetConfigReportX and again waiting for report (main subject of the TC) 

Anyway I have thought it might be an issue.

Thanks for answer.
